/**
 * @fileoverview added by tsickle
 * @suppress {checkTypes,extraRequire,uselessCode} checked by tsc
 */
/**
 * @license
 * Copyright Google Inc. All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */
import * as tslib_1 from "tslib";
import { Compiler, Injectable } from '@angular/core';
/**
 * @return {?}
 */
function unimplemented() {
    throw Error('unimplemented');
}
/**
 * Special interface to the compiler only used by testing
 *
 * \@publicApi
 */
var TestingCompiler = /** @class */ (function (_super) {
    tslib_1.__extends(TestingCompiler, _super);
    function TestingCompiler() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Object.defineProperty(TestingCompiler.prototype, "injector", {
        get: /**
         * @return {?}
         */
        function () { throw unimplemented(); },
        enumerable: true,
        configurable: true
    });
    /**
     * @param {?} module
     * @param {?} overrides
     * @return {?}
     */
    TestingCompiler.prototype.overrideModule = /**
     * @param {?} module
     * @param {?} overrides
     * @return {?}
     */
    function (module, overrides) {
        throw unimplemented();
    };
    /**
     * @param {?} directive
     * @param {?} overrides
     * @return {?}
     */
    TestingCompiler.prototype.overrideDirective = /**
     * @param {?} directive
     * @param {?} overrides
     * @return {?}
     */
    function (directive, overrides) {
        throw unimplemented();
    };
    /**
     * @param {?} component
     * @param {?} overrides
     * @return {?}
     */
    TestingCompiler.prototype.overrideComponent = /**
     * @param {?} component
     * @param {?} overrides
     * @return {?}
     */
    function (component, overrides) {
        throw unimplemented();
    };
    /**
     * @param {?} directive
     * @param {?} overrides
     * @return {?}
     */
    TestingCompiler.prototype.overridePipe = /**
     * @param {?} directive
     * @param {?} overrides
     * @return {?}
     */
    function (directive, overrides) {
        throw unimplemented();
    };
    /**
     * Allows to pass the compile summary from AOT compilation to the JIT compiler,
     * so that it can use the code generated by AOT.
     */
    /**
     * Allows to pass the compile summary from AOT compilation to the JIT compiler,
     * so that it can use the code generated by AOT.
     * @param {?} summaries
     * @return {?}
     */
    TestingCompiler.prototype.loadAotSummaries = /**
     * Allows to pass the compile summary from AOT compilation to the JIT compiler,
     * so that it can use the code generated by AOT.
     * @param {?} summaries
     * @return {?}
     */
    function (summaries) { throw unimplemented(); };
    /**
     * Gets the component factory for the given component.
     * This assumes that the component has been compiled before calling this call using
     * `compileModuleAndAllComponents*`.
     */
    /**
     * Gets the component factory for the given component.
     * This assumes that the component has been compiled before calling this call using
     * `compileModuleAndAllComponents*`.
     * @template T
     * @param {?} component
     * @return {?}
     */
    TestingCompiler.prototype.getComponentFactory = /**
     * Gets the component factory for the given component.
     * This assumes that the component has been compiled before calling this call using
     * `compileModuleAndAllComponents*`.
     * @template T
     * @param {?} component
     * @return {?}
     */
    function (component) { throw unimplemented(); };
    /**
     * Returns the component type that is stored in the given error.
     * This can be used for errors created by compileModule...
     */
    /**
     * Returns the component type that is stored in the given error.
     * This can be used for errors created by compileModule...
     * @param {?} error
     * @return {?}
     */
    TestingCompiler.prototype.getComponentFromError = /**
     * Returns the component type that is stored in the given error.
     * This can be used for errors created by compileModule...
     * @param {?} error
     * @return {?}
     */
    function (error) { throw unimplemented(); };
    TestingCompiler.decorators = [
        { type: Injectable },
    ];
    return TestingCompiler;
}(Compiler));
export { TestingCompiler };
/**
 * A factory for creating a Compiler
 *
 * \@publicApi
 * @abstract
 */
var /**
 * A factory for creating a Compiler
 *
 * \@publicApi
 * @abstract
 */
TestingCompilerFactory = /** @class */ (function () {
    function TestingCompilerFactory() {
    }
    return TestingCompilerFactory;
}());
/**
 * A factory for creating a Compiler
 *
 * \@publicApi
 * @abstract
 */
export { TestingCompilerFactory };
if (false) {
    /**
     * @abstract
     * @param {?=} options
     * @return {?}
     */
    TestingCompilerFactory.prototype.createTestingCompiler = function (options) { };
}
//# sourceMappingURL=test_compiler.js.map